package com.methods;

import java.util.Set;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class GetMethod {

	public static void main(String[] args) throws InterruptedException {

		WebDriver driver = new ChromeDriver();
		
		
		//get () used to load the driver
		    driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
		
		//getTitle() used to return title of page
		    String title = driver.getTitle();
		    System.out.println(title);
		
		//getPageSource() used to return the Source code of web page which was generated by servers
			String pageSource = driver.getPageSource();			
			//System.out.println(pageSource);
			
		//getCurrentUrl() return current page URL
			String currentUrl = driver.getCurrentUrl();
			System.out.println(currentUrl);
			
		//getWindowHandle() return the current web page ID (Which was dynamic)
			String windowHandle = driver.getWindowHandle();
			System.out.println("getWindowHandle(): "+windowHandle);
			
			Thread.sleep(5000);
			driver.findElement(By.linkText("OrangeHRM, Inc")).click();
			
		//getWindowHandles() return the current web page ID (Which was dynamic)
			Set<String> windowHandles = driver.getWindowHandles();
			
			System.out.println("windowHandles: "+ windowHandles);
		
		
		
	}

}
